name: wppdriver
description: A WhitePawnProtocol Driver written in pure Dart
version: 0.0.1
repository: https://github.com/mono424/wppdriver

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.17.10